networks:
  net:
    name: net
    driver: bridge

volumes:
  db_volume:
    name: db_volume

services:
  app:
    build: ./src
    image: ozennou/ronda_game:latest
    container_name: app
    ports:
      - 8000:8000
    environment:
      - REDIS_PASSWD=$REDIS_PASSWD
  redis:
    image: redis:7.4.1-bookworm
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWD}
    ports:
      - 6379:6379
  database:
    image: postgres:14.15-alpine3.20
    container_name: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
