name: CI Workflow

on:
    push:
        branches: [ "main" ]
        paths: ["src/**/*.py", "src/Requirements.txt", "src/script.sh", "docker-compose.yml"]
    pull_request:
        branches: [ "main" ]
        paths: ["src/**/*.py", "src/Requirements.txt", "src/script.sh", "docker-compose.yml"]

jobs:

    build:

        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v4
            - name: Create .env file
              run: |
                  cat << EOF > .env
                  POSTGRES_USER=${{ secrets.POSTGRES_USER }}
                  POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
                  REDIS_PASSWD=${{ secrets.REDIS_PASSWD }}
                  EOF
            - name: Build and Run
              run: |
                docker compose up -d
                docker ps

    test:
        runs-on: ubuntu-24.04
        needs: build
        strategy:
            # max-parallel: 3
            matrix:
              python-version: [3.9]
        steps:
            - uses: actions/checkout@v4
            - name: Set up python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                cd src
                python -m pip install --upgrade pip
                pip install -r Requirements.txt
            - name: Run tests
              run: python src/manage.py test

    push_image:
        runs-on: ubuntu-24.04
        needs: test
        steps:
            - uses: actions/checkout@v4
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build
              run: docker compose build
            - name: push docker image
              run: |
                docker tag ozennou/ronda_game:latest ozennou/ronda_game:0.0.${GITHUB_RUN_NUMBER}v
                docker push ozennou/ronda_game:0.0.${GITHUB_RUN_NUMBER}v
                docker push ozennou/ronda_game:latest
