name: CI Workflow

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            - name: test
              run: ls -la
            - uses: actions/checkout@v4
            - name: Building
              run: |
                echo hello
                ls -la
                sleep 5
