name: CI Workflow

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build
              run: |
                docker compose build
                echo ${{ secrets.ENVS }} > .env
                cat .env
            - name: Run
              run: |
                docker compose up -d
                sleep 10
                docker ps

