name: CI Workflow

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Building
              run: |
                echo hello
                docker login
                echo ${{ vars.DOCKERHUB_USERNAME }}
                echo ${{ secrets.DOCKERHUB_TOKEN }}
                sleep 5
            - name: test
              run: docker info
