name: CI Workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            -main

jobs:
    build:
        runs-on: ubuntu/latest
        steps:
            - name: test-step
              run: |
                ls -la
                echo 'hello world'
                sleep 5

